name: Build and Push Docker Image
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Use cache to speed up the build only for development branches
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/jurajama/opencv-docker:latest
        cache-from: type=gha,scope=${{ github.ref_name }}
        cache-to: type=gha,mode=max,scope=${{ github.ref_name }}
        no-cache: ${{ github.ref == 'refs/heads/main' }}
